### ISSUE TITLE
Add support for an initial setting configuration

### ISSUE THREAD

**Issue by jockebech** [jbech-linaro/hikey_auto_boot#4]
Add a new file `settings.yaml` which should contain at least
```yaml
repo:
 - bin_path: <path>
 - reference: <path>

toolchain:
 - aarch32_path: <path>
 - aarch64_path: <path>
 - default: <name>

env:
 -path: [ $PATH, $HOME ... ]

workspace:
 - path: <path>

log:
 - main: <path to main logger log file>
 - logtype_path: <path to a dir where temporary logstate files are stored>

db:
 - main: <path to main SQLite3 DB file>

```
